### ISSUE TITLE
Build failure on Centos 6 

### ISSUE THREAD

**Issue by mwarchut** [OSLockdown/OSLockdown#1]
Trying to build on a pristine build of centos 6.  Installed Development Tools group.   Followed by running of download_prerequisites.sh  placing all of the downloads into /root/bulld.

I then set all of the enviroment variables per the Bulding.txt document. 

Run of make testLocations yielded:

akefile:50: Sanity checking for required environment variables
Makefile:50: Envvar YES : NAME = oslockdown  
Makefile:50: Envvar YES : SB_VERSION = 5.0.0  
Makefile:50: Envvar YES : SB_RELEASE = opensource  
Makefile:50: IsDir  YES : SB_HOME = /root/repos/OSLockdown  
Makefile:50: IsDir  YES : JAVA_HOME = /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.151.x86_64  
Makefile:50: IsExec YES : $JAVA_HOME/bin/java = /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.151.x86_64/bin/java  
Makefile:50: IsExec YES : $JAVA_HOME/bin/javac = /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.151.x86_64/bin/javac  
Makefile:50: IsDir  NO  : (optional)JAVA_HOME2 
Makefile:50: IsExec NO  : (optional)$JAVA_HOME2/bin/java 
Makefile:50: IsExec NO  : (optional)$JAVA_HOME2/bin/javac 
Makefile:50: IsDir  YES : GSOAP_HOME = /usr/local  
Makefile:50: IsExec YES : $GSOAP_HOME/bin/wsdl2h = /usr/local/bin/wsdl2h  
Makefile:50: IsDir  YES : GRAILS_HOME = /root/build/grails-2.3.7  
Makefile:50: IsExec YES : $GRAILS_HOME/bin/grails = /root/build/grails-2.3.7/bin/grails  
Makefile:50: IsDir  YES : SAXON_HOME = /root/build/saxon-6.5.5  
Makefile:50: IsExec YES : $SAXON_HOME/saxon.jar = /root/build/saxon-6.5.5/saxon.jar  
Makefile:50: IsDir  YES : FOP_HOME = /root/build/fop-1.0  
Makefile:50: IsExec YES : $FOP_HOME/fop = /root/build/fop-1.0/fop  
Makefile:50: IsDir  YES : JAXWSRI_HOME = /root/build/jaxws-ri  
Makefile:50: IsDir  YES : DOCBOOK_STYLESHEETS = /root/build/docbook-xsl-1.74.0  
Makefile:50: IsDir  YES : $DOCBOOK_STYLESHEETS/fo = /root/build/docbook-xsl-1.74.0/fo  
Makefile:50: IsDir  YES : ANT_HOME = /root/build/apache-ant-1.9.2  
Makefile:50: IsExec YES : ANT = /root/build/apache-ant-1.9.2/bin/ant  
Makefile:50: IsExec YES : TOMCAT_ARCHIVE = /root/build/apache-tomcat-7.0.82.tar.gz  
Makefile:50: IsDir  NO  : (optional)GRAILS_DEP_HOME 
make: `testLocations' is up to date.

Running of make build ends with:

BUILD SUCCESSFUL
Total time: 41 seconds
echo "Making PDFs"
Making PDFs
make[1]: Leaving directory `/root/repos/OSLockdown/docs'
mkdir -p /root/repos/OSLockdown/build/dist
make -e -C /root/repos/OSLockdown/src/core build 
make[1]: Entering directory `/root/repos/OSLockdown/src/core'

mkdir -p /root/repos/OSLockdown/src/core/rpmbuilddir/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
/usr/bin/test -f build/oslockdown.spec
echo "Creating tarball to build RPM using build/oslockdown.spec"; \
        /bin/tar -C ../../.. --exclude=oslockdown/src/console --exclude=oslockdown/src/dispatcher --exclude=oslockdown/src/security_modules --exclude=oslockdown/src/selinux --exclude=oslockdown/cfg/docs --exclude=oslockdown/docs --exclude=*.rpm --exclude=*.log --exclude=*.pkg --exclude='.svn' --exclude=rpmbuilddir --exclude=externals -czf /root/repos/OSLockdown/src/core/rpmbuilddir/SOURCES/oslockdown.tar.gz oslockdown ; 
Creating tarball to build RPM using build/oslockdown.spec
/bin/tar: oslockdown: Cannot stat: No such file or directory
/bin/tar: Exiting with failure status due to previous errors
make[1]: *** [build-linux] Error 2
make[1]: Leaving directory `/root/repos/OSLockdown/src/core'
make: *** [build] Error 2

Not quite sure where to head from here.  All of the parts necessary to build RPM's appear to be installed.

**Comment by RobSanders** [comment]
Michael,
  I think you missed one of the notes in the readme - the 'root' of the OS Lockdown directory needs to be named 'oslockdown'.  By default the download from Git will call it either OSLockdown or OSLockdown-master, depending on whether you checked out the Master branch or did a zip download.  This is a legacy from our old build/devel procedures that we've never taken the time to fix.  It is on my personal list to fix here (as I dig up time to do so).  
  So the simple fix is to make sure the top level directory where you issue the 'make build' is named 'oslockdown'.  We're explicitly referencing that directory name when we tar up the source code in preparation for passing control to rpmbuild.

**Comment by mwarchut** [comment]
Right you are.    That's the problem with constant interruptions at my desk.   It's building now with no issues.   Thanks.
